; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = HoloCubic_AIO_Releases

[env]
platform = espressif32 @ ~3.5.0
; platform = espressif32 @ ~5.2.0
; platform = espressif32
framework = arduino

monitor_filters = esp32_exception_decoder
monitor_speed = 115200
; monitor_flags = 
; 	--eol=CRLF
; 	--echo
; 	--filter=esp32_exception_decoder
build_flags =
    ; ${env.build_flags}
    ; -D LV_FONT_MONTSERRAT_10=1
    -fPIC -Wreturn-type -Werror=return-type
    ; -D CONFIG_ARDUINO_LOOP_STACK_SIZE=10000

upload_port = COM12
; upload_port = COM6
upload_speed = 921600
board_build.partitions = partitions-no-ota.csv
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio


[env:HoloCubic_AIO_Debug]
; extends = env:HoloCubic_AIO
extends = env
board = pico32
build_flags =
  ${env.build_flags}
    -O0
    -D ARDUHAL_LOG_LEVEL=1
    


[env:HoloCubic_AIO_Releases]
; extends = env:HoloCubic_AIO
extends = env
board = pico32
build_flags =
  ${env.build_flags}
    ; -O2

[env:AIO_native_sim]
platform = native
framework =
build_flags =
    -std=c++11
    -D NATIVE_SIMULATION
    -D ARDUINO=100
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -D LV_DRV_NO_CONF
    -D USE_SDL
    -D SDL_HOR_RES=240
    -D SDL_VER_RES=240
    -lwinhttp
    -D SDL_ZOOM=2
    -D SDL_INCLUDE_PATH="\"SDL2/SDL.h\""
    -D SDL_MAIN_HANDLED
    -D LV_MEM_CUSTOM=1
    -fpermissive
    -D LV_MEM_SIZE="(128U * 1024U)"
    -Ihal/native
    -D APP_EXAMPLE_USE=1
    -D APP_ANNIVERSARY_USE=1
    -D APP_BILIBILI_FANS_USE=1
    -D APP_FILE_MANAGER_USE=0
    -D APP_GAME_2048_USE=1
    -D APP_GAME_SNAKE_USE=1
    -D APP_HEARTBEAT_USE=0
    -D APP_IDEA_ANIM_USE=0
    -D APP_MEDIA_PLAYER_USE=0
    -D APP_PICTURE_USE=1
    -D APP_PC_RESOURCE_USE=0
    -D APP_SCREEN_SHARE_USE=1
    -D APP_SETTING_USE=1
    -D APP_STOCK_MARKET_USE=1
    -D APP_WEATHER_USE=0
    -D APP_WEATHER_OLD_USE=0
    -D APP_TOMATO_USE=0
    -D APP_LHLXW_USE=0
    -D APP_WEB_SERVER_USE=0
    -fcommon
    -include FreeRTOS.h
    -I hal/native
    -I lib/FreeRTOS-Kernel/include
    -I lib/FreeRTOS-Kernel/portable/MSVC-MingW
    -I lib/lvgl-v8.3
    -I lib/lvgl-v8.3/src
    -I lib/ArduinoJson-6.x/src
    -I lib/font
    -I src
    -I src/driver
    -I src/sys
    -I src/app
    -lSDL2
    -lwinmm
    -lws2_32
build_src_filter =
    +<*>
    -<driver/display.cpp>
    -<driver/imu.cpp>
    -<driver/ambient.cpp>
    -<driver/sd_card.cpp>
    -<driver/rgb_led.cpp>
    -<driver/flash_fs.cpp>
    -<driver/lv_fs_fatfs.c>
    -<driver/lv_port_indev.c>
    -<network.cpp>
    -<app/file_manager/>
    -<app/heartbeat/>
    -<app/idea_anim/>
    -<app/LHLXW/>
    -<app/media_player/>
    -<app/pc_resource/>
    -<app/server/>
    -<app/tomato/>
    -<app/weather/>
    -<app/weather_old/>
    +<../hal/native>
    +<app/weather/lv_font_ibmplex_115.c>
lib_ignore =
    FastLED
    TFT_eSPI
    I2Cdev
    MPU6050
    LittleFS
    pubsubclient
    ESP32Time
    Arduino_GFX
    TJpg_Decoder
lib_archive = false